name: Build WASM

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add WASM Emscripten target
        run: rustup target add wasm32-unknown-emscripten

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Build backend with Emscripten
        working-directory: backend
        run: |
          source ../emsdk/emsdk_env.sh
          export CFLAGS="-fPIC"
          export RUSTFLAGS="-C link-args=-sEXPORTED_FUNCTIONS=['_wasm_execution_flow_gen','_wasm_no_flow_gen','_wasm_visualize_java_code'] -C link-args=-sEXPORTED_RUNTIME_METHODS=['cwrap','UTF8ToString','stringToUTF8','lengthBytesUTF8']"
          cargo build --target wasm32-unknown-emscripten --release

      - name: Move build output
        run: |
          rm -rf wasm
          mkdir wasm
          cp -r backend/target/wasm32-unknown-emscripten/release/*.{wasm,js} wasm/ || true
          rm -rf backend/target
          echo "WASM files moved to /wasm"

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add wasm/
          if ! git diff --cached --quiet; then
            git commit -m "Auto-build WASM"
            git push
          else
            echo "No changes to commit."
          fi